name: Auto Assign Pull Request

on:
  push

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Auto Assign Pull Request
        uses: ashishsantikari/auto-assign-pr@v0.0.1-alpha
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TEAM_SLUG: test
